
public class Main {

	public static void main(String[] args) {
		/*
		 	Even Fibonacci numbers
		 	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
			1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
			By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
		 */
		System.out.println(fibonacciNumbers());
		

	}
	
	public static int fibonacciNumbers (){
		// sum of even numbers
		int sum = 0;
		
		int num1 = 1 , num2 = 2 , add = 0;
		while(true){
			add = num1 + num2;
			if(add % 2 == 0)
				sum = sum + add;
			num1 = num2;
			num2 = add;
			if(add > 4000000)
				break;
		}
		return sum;
	}

}
